### ISSUE TITLE
how to test

### ISSUE THREAD

**Issue by TangZ315** [sudban3089/ID-Preserving-Facial-Aging#1]
Hello author, I'm interested in your project. Could you please let me know if it's possible to test it directly without going through the training process? Thank you very much!

**Comment by sudban3089** [comment]
Hello, thank you for your interest in our work. The training part of this work is essential for identity preservation. So, we need to train for each subject. We used ProFusion as baseline for a recent work (currently under review) which does testing directly and we observe that training using our method resulted in better aging with biometric preservation. I have attached our example from the current work under review (plz don't share; image is copyrighted) for illustration.
![profusion](https://github.com/sudban3089/ID-Preserving-Facial-Aging/assets/25641455/2557e32d-b1d8-4c2a-8550-9aaba54f73a0)

**Comment by 34328** [comment]
Hello author, I'm interested in your project, Can your training data be shared, just for learning

**Comment by sudban3089** [comment]
Thanks for your interest. As the original datasets do not belong to us, we are unfortunately not able to redistribute. Please access the datasets from the original authors. 

But for the purpose of learning, I have shared images of two individuals (you will find 2 subfolders of 2 individuals) from CelebA at the following link. Again we do not own CelebA dataset, the training data examples are provided only for learning purposes.
Link: [Training Data Examples](https://drive.google.com/drive/folders/10e3hM6-kLfda_28V1FvvFpqj8qo4zL3A?usp=sharing)

Note, you can use our code on any individual provided you have at least 10 images of that same individual of reasonably good quality. Hope this helps.

**Comment by 34328** [comment]
Thank you for your reply, but the Link you shared requires permission, I can't browse directly, please open relevant permission for me, the ID I apply for access is alexlzh431675@gmail.com，Once again, my most sincere thanks to you

**Comment by 34328** [comment]
Thank you for your reply, but the Link you shared requires permission, I can't browse directly, please open relevant permission for me, the ID I apply for access is [alexlzh431675@gmail.com](mailto:alexlzh431649@gmail.com)，Once again, my most sincere thanks to you！！！

**Comment by sudban3089** [comment]
Hello, relevant permissions are given, plz check now. Let me know if you still have issues downloading.

**Comment by sudban3089** [comment]
I have included IJCB2023_TrainExamples folder on the github page, you can download from there directly.
