### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by jupytera** [sudban3089/ID-Preserving-Facial-Aging#3]
Hello, I am very interested in this job. May I ask if you can provide a trained model? I would like to see the results. Thank you very much!

**Comment by sudban3089** [comment]
Hello, 
In this work, we used subject-specific customization as the one proposed in DreamBooth. Thus, we train on each subject at a time for identity preservation. We provided IJCB2023_TrainingExamples folder where you will find example images and you can use the main.py script to train and it will save the model for that subject. Then you can use last.ckpt (trained model saved in checkpoints folder) to infer aged/de-aged versions of the same subject at different age labels. Hope this helps..
